In [31]:
import sys
from pymatgen.io.vasp.outputs import Outcar, Vasprun
import ase
import os
import numpy as np
from ase.io import read
from ase.visualize import view
import matplotlib.pyplot as plt
import pandas as pd


sys.path.append("Users/toghrulazizli/Desktop/montemoregroup/")

from energyCorrelationFunctions import *
from coordsFunctions import *
from VibrationFunctions import *
from databaseFunctions import *

In [32]:
readAtoms_H2= read('/Users/toghrulazizli/Desktop/DFT/Calculations/CO2_ethanol/H2_gas_vib/OUTCAR')
print(readAtoms_H2)

Atoms(symbols='H2', pbc=True, cell=[20.0, 20.1, 20.2], calculator=SinglePointDFTCalculator(...))


In [33]:
Vib=readVibFreq('/Users/toghrulazizli/Desktop/DFT/Calculations/CO2_ethanol/H2_gas_vib/')
print(Vib)

eVFreq_prop=Vib[0]
eVFreqOrdered = np.sort(eVFreq_prop)
eVFreqOrdered

(array([0.53413594, 0.03477929, 0.0342448 ]), array([7.25500e-06, 3.47670e-05, 6.88042e-04]))


array([0.0342448 , 0.03477929, 0.53413594])

In [34]:
readAtoms_CO = read('/Users/toghrulazizli/Desktop/DFT/Calculations/CO2_ethanol/CO_gas_calc_vib/OUTCAR')
print(readAtoms_CO)

Atoms(symbols='CO', pbc=True, cell=[20.0, 20.1, 20.2], calculator=SinglePointDFTCalculator(...))


In [35]:
Vib=readVibFreq('/Users/toghrulazizli/Desktop/DFT/Calculations/CO2_ethanol/CO_gas_calc_vib/')
print(Vib)

eVFreq_prop=Vib[0]
eVFreqOrdered = np.sort(eVFreq_prop)
eVFreqOrdered

(array([0.26326274, 0.00464573, 0.00317635]), array([6.635800e-05, 3.305966e-03, 3.329339e-03]))


array([0.00317635, 0.00464573, 0.26326274])

In [36]:
readAtoms_CO2 = read('/Users/toghrulazizli/Desktop/DFT/Calculations/CO2_ethanol/CO2_gas_calc_vib/OUTCAR')
print(readAtoms_CO2)

Atoms(symbols='CO2', pbc=True, cell=[20.0, 20.1, 20.2], calculator=SinglePointDFTCalculator(...))


In [37]:
Vib=readVibFreq('/Users/toghrulazizli/Desktop/DFT/Calculations/CO2_ethanol/CO2_gas_calc_vib')
print(Vib)

eVFreq_prop=Vib[0]
eVFreqOrdered = np.sort(eVFreq_prop)
eVFreqOrdered

(array([0.29361973, 0.16328378, 0.07817546, 0.07816533, 0.00556145,
       0.00299307]), array([0.00012834, 0.00082786, 0.00245679]))


array([0.00299307, 0.00556145, 0.07816533, 0.07817546, 0.16328378,
       0.29361973])

In [38]:
#Ethylene reading atoms

readAtoms_H2O = read('/Users/toghrulazizli/Desktop/DFT/Calculations/CO2_ethanol/H2O_gas_vib/OUTCAR')
print(readAtoms_H2O)
#view(readAtoms_H2O)

Atoms(symbols='OH2', pbc=True, cell=[20.0, 20.1, 20.2], calculator=SinglePointDFTCalculator(...))


In [39]:
Vib=readVibFreq('/Users/toghrulazizli/Desktop/DFT/Calculations/CO2_ethanol/H2O_gas_vib/')
print(Vib)

eVFreq=Vib[0]
eVFreqOrdered = np.sort(eVFreq)
eVFreqOrdered

(array([0.47463492, 0.46061038, 0.19641946, 0.02271387, 0.01075526]), array([0.00082614, 0.00449367, 0.00570241, 0.01375679]))


array([0.01075526, 0.02271387, 0.19641946, 0.46061038, 0.47463492])

In [40]:
def deltaMuH2(temp, pressure):
    eVFreqOrdered= np.array([0.0342448 , 0.03477929, 0.53413594])
    
    MuH2GasPhaseEng= -6.75930865
    
    
    thermo = IdealGasThermo(vib_energies=eVFreqOrdered,
                      potentialenergy=0,
                      atoms=readAtoms_H2,
                      geometry='linear',
                      symmetrynumber=2, 
                      spin=0)
    MuH2Abs=[]
    if isinstance(pressure, np.ndarray):
        for i in pressure:
            freeEnCorr = thermo.get_gibbs_energy(temp, i, verbose = False)
            MuH2Abs.append(MuH2GasPhaseEng+freeEnCorr)
        return np.array(MuH2Abs)
            
    elif isinstance(temp, np.ndarray):
        for i in temp:
            freeEnCorr = thermo.get_gibbs_energy(i, pressure, verbose = False)
            MuH2Abs.append(MuH2GasPhaseEng+freeEnCorr)
        return np.array(MuH2Abs)
    
    else:
        freeEnCorr = thermo.get_gibbs_energy(temp, pressure, verbose = False)
        return MuH2GasPhaseEng+freeEnCorr
  

In [41]:
def deltaMuCO(temp, pressure):
    eVFreqOrdered= np.array([0.00317635, 0.00464573, 0.26326274])
    
    MuCOGasPhaseEng= -14.79618318
  
    
    thermo = IdealGasThermo(vib_energies=eVFreqOrdered,
                      potentialenergy=0,
                      atoms=readAtoms_CO,
                      geometry='linear',
                      symmetrynumber=1, 
                      spin=0)
    MuCOAbs=[]
    if isinstance(pressure, np.ndarray):
        for i in pressure:
            freeEnCorr = thermo.get_gibbs_energy(temp, i, verbose = False)
            MuCOAbs.append(MuCOGasPhaseEng+freeEnCorr)
        return np.array(MuCOAbs)
            
    elif isinstance(temp, np.ndarray):
        for i in temp:
            freeEnCorr = thermo.get_gibbs_energy(i, pressure, verbose = False)
            MuCOAbs.append(MuCOGasPhaseEng+freeEnCorr)
        return np.array(MuCOAbs)
    else:
        freeEnCorr = thermo.get_gibbs_energy(temp, pressure, verbose = False)
        return MuCOGasPhaseEng+freeEnCorr
            

In [52]:
def deltaMuCO2(temp, pressure):
    eVFreqOrdered= np.array([0.00299307, 0.00556145, 0.07816533, 0.07817546, 0.16328378,
       0.29361973])

    MuCO2GasPhaseEng= -22.98687490
  
    
    thermo = IdealGasThermo(vib_energies=eVFreqOrdered,
                      potentialenergy=0,
                      atoms=readAtoms_CO2,
                      geometry='linear',
                      symmetrynumber=2, 
                      spin=0)
    MuCO2Abs=[]
    if isinstance(pressure, np.ndarray):
        for i in pressure:
            freeEnCorr = thermo.get_gibbs_energy(temp, i, verbose = False)
            MuCO2Abs.append(MuCO2GasPhaseEng+freeEnCorr)
        return np.array(MuCO2Abs)
            
    elif isinstance(temp, np.ndarray):
        for i in temp:
            freeEnCorr = thermo.get_gibbs_energy(i, pressure, verbose = False)
            MuCO2Abs.append(MuCO2GasPhaseEng+freeEnCorr)
        return np.array(MuCO2Abs)
    else:
        freeEnCorr = thermo.get_gibbs_energy(temp, pressure, verbose = False)
        return MuCO2GasPhaseEng+freeEnCorr
            

In [53]:
cutoff = 4/1000
def getHarmonic(realFreq, imagFreq, cutoff = cutoff, gasPhase = False, verbose = True):
    ### TODO: Add in gas-phase here too
    if gasPhase == False:
        numAtomsMove = int((len(realFreq)+len(imagFreq))/3)
        eVFreqForHarm = prepFreqForHarmonic(realFreq,numAtomsMove,cutoff = cutoff)
        harmonic = HarmonicThermo(eVFreqForHarm)
        return harmonic

#a code that takes a directory and cut off, calculates the harmonic
def calc_harmonic_from_VibCalc(dirName,cutoff,verbose = True):
    Vib_freqs=readVibFreq(dirName)
    realFreq=Vib_freqs[0]
    imagFreq=Vib_freqs[1]
    if verbose: 
        print(realFreq,imagFreq)
    
    harmonic=getHarmonic(realFreq, imagFreq, cutoff = cutoff, gasPhase = False, verbose = False)
    return harmonic

def getFreeEnergy(temp, harmonic, verbose = True):
    if isinstance(temp,np.ndarray):
        freeEnergy = []
        for i in temp:
            freeEnergy += [harmonic.get_helmholtz_energy(i,verbose = verbose)] #Includes ZPE
        return np.array(freeEnergy)
    else:
        freeEnergy = harmonic.get_helmholtz_energy(temp,verbose = verbose)
        return freeEnergy

In [54]:
def deltaMuH2O(temp, pressure):
    eVFreqOrdered= np.array([0.01075526, 0.02271387, 0.19641946, 0.46061038, 0.47463492])
    
    MuH2OGasPhaseEng= -14.22024438
  
    
    thermo = IdealGasThermo(vib_energies=eVFreqOrdered,
                      potentialenergy=0,
                      atoms=readAtoms_H2O,
                      geometry='nonlinear',
                      symmetrynumber=2, 
                      spin=0)
    MuH2OAbs=[]
    if isinstance(pressure, np.ndarray):
        for i in pressure:
            freeEnCorr = thermo.get_gibbs_energy(temp, i, verbose = False)
            MuH2OAbs.append(MuH2OGasPhaseEng+freeEnCorr)
        return np.array(MuH2OAbs)
            
    elif isinstance(temp, np.ndarray):
        for i in temp:
            freeEnCorr = thermo.get_gibbs_energy(i, pressure, verbose = False)
            MuH2OAbs.append(MuH2OGasPhaseEng+freeEnCorr)
        return np.array(MuH2OAbs)
    else:
        freeEnCorr = thermo.get_gibbs_energy(temp, pressure, verbose = False)
        return MuH2OGasPhaseEng+freeEnCorr
            

In [55]:
P_H2 = 101325
P_CO = 101325
P_CO2 = 101325
T = 298.15   

In [57]:
mu_H2 = deltaMuH2(T, P_H2)
mu_CO = deltaMuCO(T, P_CO)
mu_CO2 = deltaMuCO2(T, P_CO2)
P_H2O = 3170 #Pa vapor pressure at 25C
mu_H2O = deltaMuH2O(T, P_H2O)
print("Mu H2 at T =", T, "K and P =", P_H2, "Pa is:", mu_H2, "eV")
print("Mu CO at T =", T, "K and P =", P_CO, "Pa is:", mu_CO, "eV")
print("Mu CO2 at T =", T, "K and P =", P_CO2, "Pa is:", mu_CO2, "eV")
print("Mu H2O at T =", T, "K and P =", P_H2O, "Pa is:", mu_H2O, "eV")

Mu H2 at T = 298.15 K and P = 101325 Pa is: -6.805719314942781 eV
Mu CO at T = 298.15 K and P = 101325 Pa is: -15.185624424616792 eV
Mu CO2 at T = 298.15 K and P = 101325 Pa is: -23.244516923493702 eV
Mu H2O at T = 298.15 K and P = 3170 Pa is: -14.224578688304168 eV


In [60]:
import os
import pandas as pd
import ase.io

calculation_dir = '/Users/toghrulazizli/Desktop/DFT/Calculations/CO2_ethanol/'
os.chdir(calculation_dir)
parentDir = "Vib_Calcs_CO2_act"

data = []   # this will become the DataFrame

for dirName in sorted(os.listdir(parentDir)):
    if dirName == '.DS_Store':
        continue

    dirName_calc = dirName.replace("_vib", "")

    harmonic = calc_harmonic_from_VibCalc(
        parentDir + "/" + dirName,
        cutoff=4/1000,
        verbose=False
    )

    correction = getFreeEnergy(T, harmonic, verbose=False)
    atoms = ase.io.read(calculation_dir + dirName_calc + '/OUTCAR')
    potential_energy = atoms.get_potential_energy()

    freeEnergy = potential_energy + correction

    # store everything
    data.append({
        "Structure": dirName_calc,
        "E_DFT (eV)": potential_energy,
        "G_vib_correction (eV)": correction,
        "G_total (eV)": freeEnergy,
        "Temperature (K)": T
    })

# build DataFrame
df = pd.DataFrame(data)

# set Structure as index FIRST
df = df.set_index("Structure")

# now sort by free energy WITHOUT resetting index
df = df.sort_values("G_total (eV)")

display(df)


/Users/toghrulazizli/Desktop/DFT/SettingUpCalcs/CO2_ethanol/databaseFunctions.py:17: FutureWarning: Vasp2 has been deprecated. Use the ase.calculators.vasp.Vasp class instead.
  vaspObj = Vasp2(directory=directory)


,E_DFT (eV),G_vib_correction (eV),G_total (eV),Temperature (K)
Structure,,,,
COOH_4OYPdCu100_15,-445.334283,0.707665,-444.626618,298.15
CO2_4OYPdCu100_3,-442.343327,0.347273,-441.996054,298.15
COOH_3OYPdCu_4,-438.673702,0.654197,-438.019505,298.15
CHO_4OYPdCu100_5,-437.649756,0.579582,-437.070174,298.15
CO2_3OYPdCu100_1,-435.226534,0.335825,-434.890710,298.15
CO_4OYPdCu100_2,-434.707489,0.275827,-434.431662,298.15
CO_3OYPdCu_2,-427.796436,0.258711,-427.537725,298.15
CHO_3OYPdCu_3,-424.352529,0.523146,-423.829382,298.15
4OYPdCu100_1_4,-418.753896,0.158766,-418.595130,298.15
